FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential g++ && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN uv pip install -r requirements.txt

COPY src/ /app/

ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

EXPOSE 5000

CMD ["python", "ai_companion/interfaces/discord/discord_endpoint.py"]
