FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential g++ && rm -rf /var/lib/apt/lists/*

COPY uv.lock pyproject2.toml README.md /app/

RUN uv sync --frozen --no-cache

COPY src/ /app/


ENV VIRTUAL_ENV=/app/.venv \
    PATH="/app/.venv/bin:$PATH"

RUN uv pip install -e .

EXPOSE 5000


CMD ["/app/.venv/bin/fastapi", "run", "ai_companion/interfaces/discord/discord_endpoint.py", "--port", "5000", "--host", "0.0.0.0"]

